"""
NLP Insights model for AuroHear backend.
"""

import uuid
from datetime import datetime, timedelta
from backend.database import db


class TestNLPInsights(db.Model):
    """
    Stores NLP analysis results from user feedback text.
    Generated by AI models to extract sentiment, emotions, and issues.
    Used for platform improvement and reliability assessment.
    """
    __tablename__ = 'test_nlp_insights'
    
    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))  # UUID primary key
    test_id = db.Column(db.String(36), nullable=False, index=True)  # References test session
    sentiment = db.Column(db.Text, nullable=False)  # positive, negative, neutral, mixed
    emotions = db.Column(db.JSON, default=dict)  # {"joy": 0.8, "frustration": 0.2}
    uncertainty = db.Column(db.Float, default=0.0)  # Confidence score 0.0-1.0
    issues = db.Column(db.JSON, default=list)  # [{"type": "audio", "severity": "high"}]
    intent = db.Column(db.Text, nullable=True)  # complaint, suggestion, praise, question
    created_at = db.Column(db.DateTime, default=db.func.current_timestamp(), nullable=False)
    
    # Indexes for efficient querying
    __table_args__ = (
        db.Index('idx_test_nlp_insights_test_id', 'test_id'),
        db.Index('idx_test_nlp_insights_sentiment', 'sentiment'),
        db.Index('idx_test_nlp_insights_created_at', 'created_at'),
    )
    
    def to_dict(self):
        """Convert NLP insights to dictionary for JSON responses"""
        return {
            'id': self.id,
            'test_id': self.test_id,
            'sentiment': self.sentiment,
            'emotions': self.emotions,
            'uncertainty': self.uncertainty,
            'issues': self.issues,
            'intent': self.intent,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
    
    @classmethod
    def get_sentiment_summary(cls, limit_days=30):
        """Get aggregated sentiment analysis for platform insights"""
        cutoff_date = datetime.now() - timedelta(days=limit_days)
        
        insights = cls.query.filter(cls.created_at >= cutoff_date).all()
        
        if not insights:
            return None
        
        # Count sentiments
        sentiment_counts = {}
        intent_counts = {}
        total_uncertainty = 0
        issue_types = {}
        
        for insight in insights:
            # Count sentiments
            sentiment = insight.sentiment
            sentiment_counts[sentiment] = sentiment_counts.get(sentiment, 0) + 1
            
            # Count intents
            if insight.intent:
                intent_counts[insight.intent] = intent_counts.get(insight.intent, 0) + 1
            
            # Sum uncertainty
            total_uncertainty += insight.uncertainty or 0
            
            # Count issue types
            if insight.issues:
                for issue in insight.issues:
                    issue_type = issue.get('type', 'unknown')
                    issue_types[issue_type] = issue_types.get(issue_type, 0) + 1
        
        return {
            'period_days': limit_days,
            'total_analyses': len(insights),
            'sentiment_distribution': sentiment_counts,
            'intent_distribution': intent_counts,
            'average_uncertainty': total_uncertainty / len(insights) if insights else 0,
            'common_issues': issue_types
        }
    
    @classmethod
    def get_reliability_metrics(cls, limit_days=7):
        """Get recent reliability metrics for platform monitoring"""
        cutoff_date = datetime.now() - timedelta(days=limit_days)
        
        insights = cls.query.filter(cls.created_at >= cutoff_date).all()
        
        if not insights:
            return {
                'reliability_score': None,
                'confidence_level': 'insufficient_data',
                'total_analyses': 0
            }
        
        # Calculate reliability metrics
        negative_sentiments = len([i for i in insights if i.sentiment in ['negative', 'mixed']])
        high_uncertainty = len([i for i in insights if (i.uncertainty or 0) > 0.7])
        critical_issues = len([i for i in insights if i.issues and 
                              any(issue.get('severity') == 'high' for issue in i.issues)])
        
        total = len(insights)
        
        # Reliability score (0-100, higher is better)
        negative_ratio = negative_sentiments / total
        uncertainty_ratio = high_uncertainty / total
        critical_ratio = critical_issues / total
        
        # Weighted scoring (sentiment 50%, uncertainty 30%, critical issues 20%)
        reliability_score = 100 * (1 - (negative_ratio * 0.5 + uncertainty_ratio * 0.3 + critical_ratio * 0.2))
        
        # Confidence level based on sample size and score
        if total < 10:
            confidence = 'low'
        elif total < 50:
            confidence = 'medium'
        else:
            confidence = 'high'
        
        return {
            'reliability_score': round(reliability_score, 1),
            'confidence_level': confidence,
            'total_analyses': total,
            'metrics': {
                'negative_sentiment_ratio': round(negative_ratio, 3),
                'high_uncertainty_ratio': round(uncertainty_ratio, 3),
                'critical_issues_ratio': round(critical_ratio, 3)
            }
        }